---
- name: NGINX | Install NGINX package from EPEL Repo
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - restart-application

- name: NGINX | Create NGINX config file from template
  template:
    src: ../templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - reload-data
