---
- name: iptables dnat
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 8080
    to_destination: "192.168.0.2:80"
    jump: DNAT
  tags:
    - deploy
    - iptables-dnat

- name: iptables snat
  iptables:
    table: nat
    chain: POSTROUTING
    protocol: tcp
    destination_port: 80
    to_source: "192.168.255.3"
    jump: SNAT
  tags:
    - iptables-snat