---
- name: start nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: systemctl daemon reload
  command: systemctl daemon-reload
