# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # "centos/7"
  config.vm.box = "generic/centos7"
  # vagrant-gatling-rsync is starting the sync engine
  # because you have at least one rsync folder.
  # To disable this behavior, set `config.gatling.rsync_on_startup = false` in your Vagrantfile.
  config.gatling.rsync_on_startup = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.synced_folder "common/", "/home/vagrant/common"

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.39.10", virtualbox__intnet: "mysql"
    master.vm.hostname = "master"
  end

  config.vm.define "replica" do |replica|
    replica.vm.network "private_network", ip: "192.168.39.11", virtualbox__intnet: "mysql"
    replica.vm.hostname = "replica"
  end

end
