---
- name: Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present

- name: Install Openvpn
  yum:
    name: openvpn
    state: latest

- name: Install policycoreutils
  yum:
    name: policycoreutils-python
    state: latest

- name: SELinux | openvpn_port_t add 1195, 1196
  shell: |
    semanage port -a -t openvpn_port_t -p udp 1195
    semanage port -a -t openvpn_port_t -p udp 1196
    exit 0

- name: Create openvpn directories
  shell: |
    mkdir -p /etc/openvpn/ccd
    mkdir -p /var/log/openvpn

- name: Copy "server-{tun,tap,tun-ras}.conf" file
  copy:
    src: ../files/{{item}}
    dest: /etc/openvpn/{{item}}
  loop:
    - server-tun.conf
    - server-tap.conf
    - server-tun-ras.conf

- name: Generate ta.key
  shell: |
    mkdir -p /etc/openvpn/keys/
    openvpn --genkey --secret {{ temp_dir }}easyrsa/pki/ta.key

- name: Collect server keys dirs /etc/openvpn/keys/
  shell: |
    mkdir -p /etc/openvpn/keys/{{ item }}
    chown openvpn:nobody -R /etc/openvpn/keys/
  loop:
    - private
    - issued

- name: Collect server keys /etc/openvpn/keys/
  copy:
    src: "{{ temp_dir }}easyrsa/pki/{{ item }}"
    dest: /etc/openvpn/keys/{{ item }}
    remote_src: true
    owner: openvpn
    group: nobody
    mode: '0770'
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - issued/server.crt
    - private/server.key
  notify:
    - systemctl restart openvpn@server-{tun,tap,tun-ras}.service
