---
- name: forwarding on
  shell: |
    echo 'net.ipv4.conf.all.forwarding=1'  > /etc/sysctl.conf
    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
    echo "net.ipv4.conf.default.rp_filter = 2" >> /etc/sysctl.conf
  notify:
    - restart network

- name: Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present
  tags:
    - epel-repo

- name: NGINX | Install NGINX package from EPEL Repo
  yum:
    name: nginx
    state: latest
  notify:
    - start nginx

- name: Copy "nginx.conf" file
  copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: NGINX | Create RAS Nginx index page
  copy:
    content: "Hello from RAS :)\n"
    dest: /usr/share/nginx/html/index.html
  notify:
    - restart nginx


