---
- name: systemctl restart openvpn@server-{tun,tap,tun-ras}.service
  systemd:
    name: openvpn@server-{{item}}.service
    state: restarted
  loop:
    - tun
    - tap
    - tun-ras
  become: true
