---
- name: test | demostration
  debug:
    msg: "I am {{ inventory_hostname }}"

- name: test | traceroute foreign host
  shell: traceroute {{ item }}
  loop: "{{ to }}"
  ignore_errors: false
  register: traceroute_content

- name: test | demostration result
  debug:
    msg: "{{ traceroute_content['stdout_lines'] }}"
