---
- name: Synchronize datetime | Install chrony
  yum:
    name: chrony
    state: latest
  tags:
    - configure-datetime

- name: Synchronize datetime | Turn on chronyd
  service:
    name: chronyd
    enabled: yes
    state: started
  notify:
    - systemctl daemon reload
  tags:
    - configure-datetime

- name: Rsyslog | Configure UDP | Enable ModLoad imudp
  replace:
    path: '/etc/rsyslog.conf'
    regexp: '#\$ModLoad\ imudp'
    replace: '$ModLoad imudp'
    backup: yes # TODO: что это значит
  notify:
    - restart rsyslog
  tags:
    - rsyslog-configure
    - rsyslog-enable-udp

- name: Rsyslog | Configure UDP | Enable UDPServerRun 514
  replace:
    path: '/etc/rsyslog.conf'
    regexp: '#\$UDPServerRun\ 514'
    replace: "$UDPServerRun {{ rsyslog['port'] }}"
  notify:
    - restart rsyslog
  tags:
    - rsyslog-configure
    - rsyslog-enable-udp

- name: Rsyslog | open UDP ports
  ansible.builtin.shell: |
    yum install -y policycoreutils-python-2.5-34.el7.x86_64
    policycoreutils-python-2.5-34.el7.x86_64
    semanage port -m -t syslogd_port_t -p udp 514
    iptables -A INPUT -p udp --dport 514 -j ACCEPT
    exit 0
  tags:
    - rsyslog-configure
    - rsyslog-enable-udp
    - open-udp-ports

- name: Rsyslog | Configure TCP | Enable ModLoad imtcp
  replace:
    path: '/etc/rsyslog.conf'
    regexp: '#\$ModLoad\ imtcp'
    replace: '$ModLoad imtcp'
    backup: yes # TODO: что это значит
  notify:
    - restart rsyslog
  tags:
    - rsyslog-configure
    - rsyslog-enable-tcp

- name: Rsyslog | Configure TCP | Enable InputTCPServerRun 514
  replace:
    path: "/etc/rsyslog.conf"
    regexp: '#\$InputTCPServerRun\ 514'
    replace: "$InputTCPServerRun {{ rsyslog['port'] }}"
  notify:
    - restart rsyslog
  tags:
    - rsyslog-configure
    - rsyslog-enable-tcp

- name: Rsyslog | open TCP ports
  ansible.builtin.shell: |
    yum install -y policycoreutils-python-2.5-34.el7.x86_64
    policycoreutils-python-2.5-34.el7.x86_64
    semanage port -m -t syslogd_port_t -p tcp 514
    iptables -A INPUT -p tcp --dport 514 -j ACCEPT
    exit 0
  tags:
    - rsyslog-configure
    - rsyslog-enable-tcp
    - open-tcp-ports

- name: Rsyslog | Change log template formatting (make timestamp better)
  replace:
    path: '/etc/rsyslog.conf'
    regexp: '\$ActionFileDefaultTemplate\ RSYSLOG_TraditionalFileFormat'
    replace: '$ActionFileDefaultTemplate RSYSLOG_FileFormat'
  notify:
    - restart rsyslog
  tags:
    - rsyslog-configure
    - rsyslog-change-log-formatting

# TODO: put at standalone Yml
- name: Rsyslog | clear /etc/rsyslog.d/ and /var/log/rsyslog/
  ansible.builtin.shell: |
    rm -rf /etc/rsyslog.d/*
    rm -rf /var/log/rsyslog/*
    rm -f /var/log/pcca/change.log
    exit 0
  tags:
    - rsyslog-rules-configure
    - clear-etc-rsyslogd

- name: Rsyslog critical
  template:
    src: ../templates/{{ file }}
    dest: /etc/rsyslog.d/{{ file }}
  vars:
    file: 'critical.conf'
  notify:
    - restart rsyslog
  tags:
    - rsyslog-rules-configure
    - rsyslog-critical

- name: Rsyslog local5
  template:
    src: ../templates/{{ file }}
    dest: /etc/rsyslog.d/{{ file }}
  vars:
    file: 'local5.conf'
  notify:
    - restart rsyslog
  tags:
    - rsyslog-rules-configure
    - rsyslog-local5

- name: Rsyslog info
  template:
    src: ../templates/{{ file }}
    dest: /etc/rsyslog.d/{{ file }}
  vars:
    file: 'info.conf'
  notify:
    - restart rsyslog
  tags:
    - rsyslog-rules-configure
    - rsyslog-info

- name: Rsyslog nginx
  template:
    src: ../templates/programable.conf
    dest: /etc/rsyslog.d/{{ program['file_name'] }}.conf
  vars:
    program: "{{ programs['nginx'] }}"
  notify:
    - restart rsyslog
  tags:
    - rsyslog-rules-configure
    - rsyslog-nginx

- name: Rsyslog self-written monitoring
  template:
    src: ../templates/programable.conf
    dest: /etc/rsyslog.d/{{ program['file_name'] }}.conf
  vars:
    program: "{{ programs['audit'] }}"
  notify:
    - restart rsyslog
  tags:
    - rsyslog-rules-configure
    - rsyslog-path-contents-change-audit
