---

- name: Rsyslog | Configure TCP | Enable ModLoad imtcp
  replace:
    path: '/etc/rsyslog.conf'
    regexp: '#\$ModLoad\ imtcp'
    replace: '$ModLoad imtcp'
    backup: yes # TODO: что это значит
  notify:
    - restart rsyslog
  tags:
    - rsyslog-enable-tcp
    - rsyslog-configure

- name: Rsyslog | Configure TCP | Enable InputTCPServerRun 514
  replace:
    path: '/etc/rsyslog.conf'
    regexp: '#\$InputTCPServerRun\ 514'
    replace: '$InputTCPServerRun 514'
  notify:
    - restart rsyslog
  tags:
    - rsyslog-enable-tcp
    - rsyslog-configure

- name: Rsyslog | Configure log template formatting
  replace:
    path: '/etc/rsyslog.conf'
    regexp: '\$ActionFileDefaultTemplate\ RSYSLOG_TraditionalFileFormat'
    replace: '$ActionFileDefaultTemplate RSYSLOG_FileFormat'
  notify:
    - restart rsyslog
  tags:
    - rsyslog-change-log-formatting
    - rsyslog-configure

- name: Rsyslog | Config content
  ansible.builtin.shell: cat /etc/rsyslog.conf
  register: rsyslog_contents
  tags:
    - rsyslog-rules-configure
    - rsyslog-configure

# EOF
- name: Rsyslog | Configure rules
  lineinfile:
    insertafter: '#### RULES ####'
    path: '/etc/rsyslog.conf'
    line: |

      # It must be before any standard rules, because '*.info' is ignored
      # Remote logging
      $template logging,"/var/log/rsyslog/%HOSTNAME% - %FROMHOST-IP%/%PROGRAMNAME%.log"
      #if $programname contains 'nginx' then ?logging
      #if $programname contains 'path_contents_change_audit' then ?logging
      # & ~
      #*.=crit ?logging
      *.* ?logging
  when: rsyslog_contents.stdout.find('# Remote logging') == -1
  notify:
    - restart rsyslog
  tags:
    - rsyslog-rules-configure
    - rsyslog-configure
