# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :hw023web => {
        :config => "centos/7",
        :ip_addr => '192.168.23.80'
  },
  :hw023log => {
        :config => "centos/7",
        :ip_addr => '192.168.23.90'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:config]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL

          # config.vm.define "guest" do |guest|
          #   guest.vm.provision "shell", path: "hw015.sh"
          #   guest.vm.hostname = "guest"
          # end
      end
  end
end