---
- name: test | http | curl
  shell: curl 192.168.0.2:80
  register: curl_content

- name: test | http | index page content
  debug:
    msg: "{{ curl_content['stdout'] }}"

#- name: test | traceroute foreign host
#  local_action:
#    module: lineinfile
#    dest: "../../files/tests-reports/{{ inventory_hostname }} - {{ item['cmd'] }}.txt"
#    line: "{{ item['stdout'] }}"
#    create: yes
#  loop: "{{ traceroute_content['results'] }}"
#  changed_when: true