---
- name: set gateway for interface v-*
  shell: |
    echo "{{ gateway['src'] }} via {{ gateway['via'] }}" > /etc/sysconfig/network-scripts/route-{{ gateway['name'] }}
    exit 0
  vars:
    gateway: "{{ networks_hosts[inventory_hostname]['gateway'] }}"
  notify:
    - systemctl-restart-network
  tags:
    - deploy
    - route-on

- name: /etc/sysconfig/network-scripts/ifcfg-eth0 | content
  command: /bin/cat /etc/sysconfig/network-scripts/ifcfg-{{ gateway['name'] }}
  vars:
    gateway: "{{ networks_hosts[inventory_hostname]['gateway'] }}"
  register: ifcfg_ethX_content
  tags:
    - deploy
    - ifcfg-ethX-default-gw

- name: /etc/sysconfig/network-scripts/ifcfg-ethX | GATEWAY=<ip> | setup if did not set
  lineinfile:
    insertafter: EOF
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ gateway['name'] }}
    line: "GATEWAY={{ gateway['via'] }}"
  when: not ifcfg_ethX_content is search("GATEWAY=")
  vars:
    gateway: "{{ networks_hosts[inventory_hostname]['gateway'] }}"
  notify:
    - systemctl-restart-network
  tags:
    - deploy
    - ifcfg-ethX-default-gw

# sed -i 's/0.1/222.22/g'  /etc/sysconfig/network-scripts/ifcfg-eth1
# sed -i 's/asd//g'  /etc/sysconfig/network-scripts/ifcfg-eth1
- name: /etc/sysconfig/network-scripts/ifcfg-ethX | GATEWAY=<ip> | replace
  replace:
    path:  /etc/sysconfig/network-scripts/ifcfg-{{ gateway['name'] }}
    regexp: 'GATEWAY=[\w\.]*'
    replace: "GATEWAY={{ gateway['via'] }}"
  when: ifcfg_ethX_content is search("GATEWAY=")
  vars:
    gateway: "{{ networks_hosts[inventory_hostname]['gateway'] }}"
  notify:
    - systemctl-restart-network
  tags:
    - deploy
    - ifcfg-ethX-default-gw