---
- name: start nginx
  systemd:
    name: nginx
    state: started

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart network
  systemd:
    name: network
    state: restarted
