# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "pxeserver" do |server|
        config.vm.box = 'centos/8.3'
        config.vm.box_url = 'https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.3.2011-20201204.2.x86_64.vagrant-virtualbox.box'
        config.vm.box_download_checksum = 'fee51a026c1caa9d88a8c74f09352ef4b7606952285cdf2888ea062a8eee499f'
        config.vm.box_download_checksum_type = 'sha256'
        config.gatling.rsync_on_startup = false

        server.vm.host_name = 'pxeserver'
        server.vm.network :private_network,
                         ip: "10.0.0.20",
                         virtualbox__intnet: 'pxenet'

        # server.vm.network "forwarded_port", guest: 80, host: 8081

        server.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end

        # config.vm.network "forwarded_port", guest: 80, host: 8888

        # ENABLE to setup PXE
        # server.vm.provision "shell",
        #  name: "Setup PXE server",
        #  path: "setup_pxe.sh"
        # end
    end

    # Cent OS 8.2
    # config used from this
    # https://github.com/eoli3n/vagrant-pxe/blob/master/client/Vagrantfile
    config.vm.define "pxeclient" do |pxeclient|
        pxeclient.vm.box = 'centos/7'                       # <------ изначально стоит Сentos 7
        pxeclient.vm.host_name = 'pxeclient'
        pxeclient.vm.network :private_network, ip: "10.0.0.21"
        pxeclient.vm.provider :virtualbox do |vb|
            vb.memory = "2048"
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize [
                'modifyvm', :id,
                '--nic1', 'intnet',
                '--intnet1', 'pxenet',
                '--nic2', 'nat',
                '--boot1', 'net',
                '--boot2', 'none',
                '--boot3', 'none',
                '--boot4', 'none'
            ]
        end
    end

end
