---
- name: systemctl-restart-dhcpd
  systemd:
    state: restarted
    name: dhcpd
#
#- name: systemctl-restart-nfs-server
#  systemd:
#    state: restarted
#    name: nfs-server

- name: enable nginx
  systemd:
    name: nginx
    enabled: yes

- name: start nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: reload nginx
  systemd:
    state: reloaded
    name: nginx

- name: restart nginx
  systemd:
    state: restarted
    name: nginx