# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :server => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.31.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ethernet_tun"},
            {ip: '192.168.32.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "ethernet_tap"},
            {ip: '192.168.33.2', adapter: 4, netmask: "255.255.255.0"}, # ethernet_tun_ras, hostonly interface, must not be *.1
        ],
    },
    :clienttun => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.31.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ethernet_tun"},
        ]
    },
    :clienttap => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.32.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ethernet_tap"},
        ]
    },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
        config.gatling.rsync_on_startup = false
        config.vm.define boxname do |box|

            box.vm.provider "virtualbox" do |v|
                v.memory = 256
                v.cpus = 1
            end

            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            box.vm.synced_folder "guest/", "/home/vagrant/common"

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL

        end
    end
end
