# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :inetRouter => {
        :box_name => "centos/7",
        :net => [
            {adapter: 2, virtualbox__intnet: "channel_1",},
            {adapter: 3, virtualbox__intnet: "channel_2",}
        ]
    },
    :centralRouter => {
        :box_name => "centos/7",
        :net => [
            {adapter: 2, virtualbox__intnet: "channel_1",},
            {adapter: 3, virtualbox__intnet: "channel_2",},
        ]
    },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
        config.gatling.rsync_on_startup = false
        config.vm.define boxname do |box|
            box.vm.provision "shell", run: "always", inline: <<-SHELL

                systemctl stop NetworkManager    # <--- No once anymore
                systemctl disable NetworkManager # <--- No once anymore

                systemctl enable network.service
                systemctl start network.service

            SHELL

            config.vm.provider "virtualbox" do |v|
                v.memory = 256
                v.cpus = 1
            end

            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL

        end
    end
end
