---
- name: Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Configure nginx
  template:
    src: ../files/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - start nginx

- name: index.html
  template:
    src: ../files/usr/share/nginx/html/index.html
    dest: /usr/share/nginx/html/index.html
  notify:
    - restart nginx
