---
- name: /etc/sysconfig/network | "NOZEROCONF=yes" | I don't want 169.254.0.0/16 network at default
  shell: |
    echo "NOZEROCONF=yes" > /etc/sysconfig/network
    exit 0
  ignore_errors: false

- name: rm -f modprobe.conf
  shell: |
    rm -f /etc/modprobe.conf
    exit 0

- name: Configure bond in modprobe.conf
  shell: |
    echo "alias {{ item.DEVICE }} bonding" >> /etc/modprobe.conf
    echo "options {{ item.DEVICE }} {{ item.BONDING_OPTS }} " >> /etc/modprobe.conf
    exit 0
  loop: "{{ networks_hosts[inventory_hostname]['bonds'] }}"
  when: item['TYPE'] is defined and item['TYPE'] == "Bond"

- name: /etc/sysconfig/network-scripts/ifcfg-<bonded> | delete interfaces
  shell: |
    rm -f /etc/sysconfig/network-scripts/ifcfg-{{ item.DEVICE }}
    exit 0
  loop: "{{ networks_hosts[inventory_hostname]['bonds'] }}"

- name: /etc/sysconfig/network-scripts/ifcfg-<bonded> | create bond
  copy:
    #content: "{% for key in item %}{% if key != 'BONDING_OPTS' %}{{ key }}={{ item[key] }}\n{% endif %}{% endfor %}"
    content: "{% for key in item %}{{ key }}={{ item[key] }}\n{% endfor %}"
    dest: /etc/sysconfig/network-scripts/ifcfg-{{item.DEVICE}}
  loop: "{{ networks_hosts[inventory_hostname]['bonds'] }}"
  notify:
    - systemctl-restart-network
