---
- name: Check openvpn client
  shell: "{{ item }}"
  loop:
    - systemctl status openvpn@client.service
    - /sbin/ip add show tun0
  register: check_content

- name: Store check to files
  local_action:
    module: copy
    content: "{{ item['stdout'] }}"
    dest: "../../files/{{ inventory_hostname }}-{{ item['cmd'] | replace('/', '_') | replace(' ', '-') }}.txt"
  loop: "{{ check_content['results'] }}"

