---
- name: Check openvpn client
  shell: '{{ item }}'
  loop:
    - systemctl status openvpn@client.service
    - "/sbin/ip addr | awk -v RS='(^|\n)[0-9]+: ' '/^(tun|tap)[0-9]*:/ {print}'"
  register: check_content

- name: Store check to files
  local_action:
    module: copy
    content: "{{ item['stdout'] }}"
    dest: "../../files/{{ inventory_hostname }}-{{ item['cmd'] | replace('/', '_') | replace(' ', '-') }}.txt"
  loop: "{{ check_content['results'] }}"

