---
- name: Playbook of "net.ipv4.conf.all.forwarding = 1"
  hosts:
    - inetRouter
    - centralRouter
    - office1Router
    - office2Router
#    - centralServer
#    - office1Server
#    - office2Server
  become: yes
  roles:
    - role: '../roles/forwarding-on'