---
- name: Playbook of "net.ipv4.conf.all.forwarding = 1"
  hosts:
    - inetRouter
    - centralRouter
    - centralServer
    - office1Router
    - office1Server
    - office2Router
    - office2Server
  become: yes
  roles:
    - role: '../roles/gateway-on'
