---
- name: Playbook of client initialization
  hosts:
#    - inetRouter
    - centralRouter
    - centralServer
#    - office1Router
#    - office1Server
#    - office2Router
#    - office2Server
  become: yes
  roles:
    - role: '../roles/network-hosts'
      tags:
      - deploy
