---
- name: test | demostration
  debug:
    msg: "Run from inventory: {{ inventory_hostname }}"

- name: test | traceroute foreign host
  shell: traceroute {{ item }}
  loop: "{{ to }}"
  ignore_errors: false
  register: traceroute_content

- name: test | result file output
  local_action:
    module: copy
    content: "{{ item['stdout'] }}"
    dest:  "../../files/tests-reports/{{ inventory_hostname }} - {{ item['cmd'] }}.txt"
  loop: "{{ traceroute_content['results'] }}"
